name: Mall Customers Clustering Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Step 4: Run clustering script
      - name: Run clustering
        run: |
          python model/mall.py

      # Step 5: Run Flask app test (headless)
      - name: Test Flask App
        run: |
          nohup python model/app.py > app.log 2>&1 &
          sleep 5
          curl -f http://127.0.0.1:5000/ || (cat app.log && exit 1)

      # Step 6: Upload results (clustered CSV)
      - name: Upload clustered results
        uses: actions/upload-artifact@v4
        with:
          name: clustered-data
          path: model/Mall_Customers_Clustered.csv